### ISSUE TITLE
seeing crashes with "switchtec status" command

### ISSUE THREAD

**Issue by wmohanlon** [Microsemi/switchtec-user#317]
We're seeing crashes with "switchtec status /dev/switchtec0".

I've traced the issue part way to this code:

lib/switchtec.c:
static void generate_lane_str(struct switchtec_status *s)
{
	int i, l;

	for (i = 0; i < s->cfg_lnk_width; i++)
		s->lanes[i] = 'x';

If cfg_lnk_width is > 16, there's a buffer overrun while writing "x".

At the moment, however, I don't know why cfg_lnk_width is garbage.  It's possible that the problem is local to our hardware.  It bothers me that every one doesn't see this.  :-)

**Comment by kelvin-cao** [comment]
Hi @wmohanlon,

It's unlikely the cfg_lnk_width would > 16, do you know what's the bifurcation of your switch? Thanks.
