### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by wak-google** [Microsemi/switchtec-user#327]
It's been some months without a new release and some fixes have landed to the tree. Any plans to make a new release?

**Comment by kelvin-cao** [comment]
@wak-google There are still some fixes to come, hopefully we can have a new release in a couple of weeks.

**Comment by brandonkimbk** [comment]
Hi Kelvin, do you happen to have an update on this? Thanks!

**Comment by kelvin-cao** [comment]
@brandonkimbk we have a new release: https://github.com/Microsemi/switchtec-user/releases/tag/v4.0.
