### ISSUE TITLE
fw.c should not toggle image before a download operation

### ISSUE THREAD

**Issue by vermilionink** [Microsemi/switchtec-user#44]
function switchtec_fw_write_fd() should not perform operation
cmd.hdr.dont_activate = !!dont_activate;
before downloading the image, as it the image is toggled regardless of whether the operation completes successfully.

**Comment by wesleywesley** [comment]
@vermilionink 

Image Activation Option (0x001)
This field specifies whether the download is activated automatically on completion:
0 - Image is activated after download is completed
1 - Image is not activated after download is completed
Note:
When this flag is set, the Toggle sub-command must be used to activate the downloaded image.
