### ISSUE TITLE
nvme information only displayed for management EP in status command

### ISSUE THREAD

**Issue by omermargolin** [Microsemi/switchtec-user#59]
Hi,

Using ./switchtec status 0 command, the data for a populated slot will include the device information only in the queried partition management EP.
In the below example, information exists for partition 0 logical port 25 - The device is nvme4.
But for partition 1 (which is UPS only) there is no device information. 

Partition 0:
    Logical Port ID 25 (DSP):
        Phys Port ID:           40 (Stack 5, Port 0)
        Bus-Dev-Func:           0000:3a:18.0
        Status:                 UP
        LTSSM:                  L0
        Max-Width:              x2
        Neg Width:              x2
        Rate:                   Gen3 - 8 GT/s  1.97 GB/s
        Out Bytes:              289 kB
        In Bytes:               3.01 MB
        ACS:                    P2P Redirected
        Device:                 11f8:8606 (0000:53:00.0)
                                nvme4

Partition 1:
    Logical Port ID 2 (DSP):
        Phys Port ID:           17 (Stack 2, Port 1)
        Status:                 UP
        LTSSM:                  L0
        Max-Width:              x2
        Neg Width:              x2
        Rate:                   Gen3 - 8 GT/s  1.97 GB/s
        Out Bytes:              99.1 kB
        In Bytes:               2.82 MB

Can you please add the device information regardless of the queried management EP and the partition to which it belongs?

**Comment by lsgunth** [comment]
There's no way for switchtec-cli to find out what's attached on another partition / host. It can only get this information for the local partition.
