### ISSUE TITLE
Makefile doesn't properly install libswitchtec.so

### ISSUE THREAD

**Issue by cmicalizzi** [Microsemi/switchtec-user#6]
The Makefile doesn't configure the libraries that are created. 
One has to specifically do ldconfig /usr/local/lib to get the libraries installed.
there are lines with LDCONFIG in the makefile but the libraries aren't configured.
Not about to try and fix the makefile as I don't want to screw it up.
Who ever did this probably configured them by hand and didn't remove them when they tested the makefile. I found this by trying to build and run examples/temp

**Comment by lsgunth** [comment]
This sounds like an issue with your OS.

You should have /usr/local/lib in /etc/ld.so.conf (or somewhere in /etc/ld.so.conf.d). Otherwise subsequent ldconfig calls will not include that directory in the new cache. Most machines I've used include this by default.

Logan

**Comment by cmicalizzi** [comment]
Thanks, I checked the "config" on a generic Ubuntu system and it's okay. The problem machine is running Oracle Linux which is made from a redhat distro.

**Comment by cmicalizzi** [comment]
Logan,

     I checked one of my generic Ubuntu systems and it does have 
/usr/local/lib in /etc/ld.so.conf
     The system that failed is running Oracle Linux which is made from a 
Redhat distro.
     Thanks for the help.

chuck
